version: '3.5'
services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "-Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8"
    ports:
      - target: 8080
        published: 18080
        mode: host
    networks:
      - middleware
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

networks:
  middleware:
    external: true
