version: '3.5'

services:
  wap:
    build:
      context: ../wap
      dockerfile: $PWD/wap/Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - middleware
  web:
    build:
      context: ../web
      dockerfile: $PWD/web/Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - middleware
  wap-api:
    build:
      context: ../wap-api
      dockerfile: $PWD/wap-api/Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "28081:28080"
    networks:
      - middleware
  web-api:
    build:
      context: ../web-api
      dockerfile: $PWD/web-api/Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "28080:28080"
    volumes:
      - /home/data/file:/usr/local/tmp/web-api/uploads/
    networks:
      - middleware
  nginx:
    image: nginx:1.20
    user: root
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
    command:
      bash -c "mkdir -p /usr/lib/nginx/proxy_tmp && \
      mkdir -p /usr/lib/nginx/proxy_cache/imgcache && \
      chown -R nginx:nginx /usr/lib/nginx/proxy* && \
      /docker-entrypoint.sh nginx -g 'daemon off;'"
    networks:
      middleware:
    ports:
      - target: 8888
        published: 8888
        mode: host
      - target: 9999
        published: 9999
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "nginx_log:/var/log/"
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf/cors.conf:/etc/nginx/cors.conf"
      - "./nginx/conf/conf.d/:/etc/nginx/conf.d/"
      # - "nginx_uploads:/etc/nginx/data/uploads"
      - /home/data/file/:/etc/nginx/data/uploads

volumes:
  nginx_log:
#   nginx_uploads:

networks:
  middleware:
    external: true
