
services:
  frp-ssh:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2522:22"
    environment:
      - TZ="Asia/Shanghai"
      - serverAddr="116.1.1.1"
      - serverPort=7000
      - client_name="ssh"
      - ssh_remotePort=6000
    restart: unless-stopped
    privileged: true 
