version: '3.5'
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    user: root
    dns:
      - 114.114.114.114
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /bin/docker:/bin/docker
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "-Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8"
      https_proxy: http://10.0.16.17:7890
      http_proxy: http://10.0.16.17:7890
      all_proxy: socks5://10.0.16.17:7890
    ports:
      - target: 8080
        published: 18080
        mode: host
    networks:
      - middleware
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

networks:
  middleware:
    external: true

volumes:
  jenkins_home:
