# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: doc-record
description: doc-record
author: doc-record
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
url: http://localhost:4000
root: /
permalink: :title/

# Directory
source_dir: source
public_dir: public
archive_dir: archives
category_dir: categories
tag_dir: tags
skip_render: 
  - "**/temp/**"
  - "**/templates/**"
  - "**/*.yaml"
  - "**/*.yml"

# Writing
new_post_name: :title.md
default_layout: post
external_link:
  enable: true
post_asset_folder: false
highlight:
  enable: true
  line_number: false
  wrap: true
prismjs:
  enable: false

# Category & Tag
default_category: uncategorized

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 15

# Extensions
theme: next
theme_config:
  scheme: Mist
  menu:
    home: / || home
    archives: /archives/ || archive
    tags: /tags/ || tags

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
