# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: doc-record
description: doc-record
author: doc-record
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
url: https://183461750.github.io/doc-record
root: /doc-record/
permalink: :title/

# Directory
source_dir: source
public_dir: public
archive_dir: archives
category_dir: categories
tag_dir: tags
skip_render: 
  - "**/temp/**"
  - "**/templates/**"
  - "**/*.yaml"
  - "**/*.yml"

# Writing
new_post_name: :title.md
default_layout: post
external_link:
  enable: true
  field: site
  exclude: ''
post_asset_folder: true
relative_link: false
highlight:
  enable: true
  line_number: false
  wrap: true
prismjs:
  enable: false

# Category & Tag
default_category: uncategorized

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 15

# Extensions
theme: next

# Search
search:
  path: search.xml
  field: post
  content: true
  format: html

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
