title: doc-record
description: doc-record
baseurl: ""
url: ""

# Theme settings
theme: just-the-docs

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Just the Docs settings
just_the_docs:
  collections:
    docs:
      name: Documentation

# Search settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: true

# Back to top link
back_to_top: true
back_to_top_text: "回到顶部"

# Color scheme
color_scheme: dark

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - .git/
  - .github/
  - .vscode/
  - scripts/
  - .frontmatter/
