# Scheme
scheme: Mist

# Menu
menu:
  home: /doc-record/ || fa fa-home
  archives: /doc-record/archives/ || fa fa-archive
  tags: /doc-record/tags/ || fa fa-tags

# Sidebar
sidebar:
  position: left
  display: always

# CDN Settings
vendors:
  # Internal version: local
  internal: local
  # Plugin version: local
  plugins: local

# Disable unused features
motion:
  enable: false

# Local Search
local_search:
  enable: true
  path: search.xml
  top_n_per_article: 1
  unescape: false
  preload: false

# Post meta display settings
post_meta:
  item_text: false
  created_at: true
  updated_at: false
  categories: true
  tags: true

# Assets
css: css
js: js
images: images

# Disable all third-party integrations
creative_commons:
  enable: false
busuanzi_count:
  enable: false
github_banner:
  enable: false
follow_me:
  enable: false
baidu_analytics:
  enable: false
google_analytics:
  enable: false

# Disable comments
comments:
  enable: false

# Disable unnecessary features
quicklink:
  enable: false
mediumzoom:
  enable: false
lazyload:
  enable: false
fancybox:
  enable: false 