# Site settings
title: Doc Record
description: Documentation Repository
baseurl: "/doc-record"
url: ""

# 主题设置
remote_theme: just-the-docs/just-the-docs

# 图片路径设置
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"
      nav_order: 1000
  - scope:
      path: "kubernetes"
    values:
      nav_fold: true
  - scope:
      path: "docker"
    values:
      nav_fold: true

# 导航设置
nav:
  enable: true

# 集合设置
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Just the Docs 配置
just_the_docs:
  collections:
    docs:
      name: Documentation

# GitHub 链接
aux_links:
  "GitHub":
    - "https://github.com/183461750/doc-record"

# 搜索配置
search_enabled: true
search:
  heading_level: 3
  previews: 2
  preview_words_before: 3
  preview_words_after: 3

# 主题
color_scheme: dark

# 功能开关
enable_copy_code_button: true

# 排除的文件和目录
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
