import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 自动从文档文件夹结构生成侧边栏
  docSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
