version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15673:15672
      - 5673:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - middleware
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

networks:
  middleware:
    external: true

volumes:
  rabbitmq_data: