version: '3.5'
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    environment:
      TZ: "Asia/Shanghai"
      JAVA_OPTS: "-Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - middleware
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

networks:
  middleware:
    external: true

volumes:
  jenkins_home:
