version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 3230:80
    networks:
      - middleware

networks:
  middleware:
    external: true
