version: '3.5'

services:
  mysql:
    image: "docker.io/mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_USER: 'root' # 用于配置普通用户
      # MYSQL_PASS: 'root' # 用于配置普通用户
    ports:
      - "3306:3306"
    networks:
      - middleware
    volumes:
      - mysql_conf:/etc/mysql/conf.d
      - mysql_logs:/logs
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

networks:
  middleware:
    external: true

volumes:
  mysql_conf:
  mysql_logs:
  mysql_data:
