version: "3"

services:

  nginx:
    image: nginx:1.15-alpine
    environment:
      TZ: "Asia/Shanghai"
      SUB_DOMAIN_MQ: "mq.*"
    command:
      " bash -c /etc/nginx/entrypoint.sh && nginx -g daemon off; "
    networks:
      middleware:
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.client==true

    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./nginx/entrypoint.sh:/etc/nginx/entrypoint.sh"
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf/cors.conf:/etc/nginx/cors.conf"
      - "./nginx/conf/template:/etc/nginx/template"
      - "nginx:/var/log/"

volumes:
  nginx:

networks:
  middleware:
    external: true