
services:
  headscale:
    image: headscale/headscale:latest
    pull_policy: always
    container_name: headscale
    restart: unless-stopped
    command: serve
    volumes:
      - ./headscale/config:/etc/headscale
      # - ./headscale/data:/var/lib/headscale
    labels:
      - traefik.enable=true
      - traefik.http.routers.headscale-rtr.rule=Host(`headscale.127.0.0.1.nip.io`) # you might want to add: && Host(`your.domain.name`)"
      # - traefik.http.routers.headscale-rtr.rule=Host(`headscale.127.0.0.1.nip.io`) && PathPrefix(`/api`) # you might want to add: && Host(`your.domain.name`)"
      # - traefik.http.routers.headscale-rtr.rule=PathPrefix(`/`) # you might want to add: && Host(`your.domain.name`)"
      - traefik.http.services.headscale-svc.loadbalancer.server.port=8080

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    pull_policy: always
    container_name: headscale-ui
    restart: unless-stopped
    labels:
      - traefik.enable=true
      # - traefik.http.routers.headscale-ui-rtr.rule=Host(`headscale-ui.127.0.0.1.nip.io`) && PathPrefix(`/web`) # you might want to add: && Host(`your.domain.name`)"
      - traefik.http.routers.headscale-ui-rtr.rule=Host(`headscale-ui.127.0.0.1.nip.io`) # you might want to add: && Host(`your.domain.name`)"
      # - traefik.http.routers.headscale-ui-rtr.rule=PathPrefix(`/web`) # you might want to add: && Host(`your.domain.name`)"
      - traefik.http.services.headscale-ui-svc.loadbalancer.server.port=8080
      # - traefik.http.services.headscale-ui-svc.loadbalancer.server.port=8443

  traefik:
    image: traefik:latest
    pull_policy: always
    restart: unless-stopped
    container_name: traefik
    command:
      - --api.insecure=true # remove in production
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --global.sendAnonymousUsage=false
    ports:
      # http://headscale-ui.127.0.0.1.nip.io:880/web/settings.html
      - 880:80
      - 8443:443
      # http://localhost:8080/dashboard/#/
      - 8080:8080 # web UI (enabled with api.insecure)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./traefik/certificates:/certificates
