version: "3.7"

services:

  headscale:
    image: headscale/headscale:latest
    restart: unless-stopped
    ports:
      - target: 8080
        published: 8888
        mode: host
      - target: 9090
        published: 9999
        mode: host
    volumes:
      # Please change <CONFIG_PATH> to the fullpath of the config folder just created
      - ./config:/etc/headscale
    command: serve

  openresty:
    image: openresty/openresty:alpine
    ports:
      - "19999:443"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/certs:/usr/local/openresty/nginx/conf/certs
    restart: always
