services:

  ssh:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    environment:
      TZ: "Asia/Shanghai"
    restart: always

  docker:
    build:
      context: .
      dockerfile: Dockerfile_docker
      # args:
      #   HTTP_PROXY: "http://10.0.4.25:7890"
      #   HTTPS_PROXY: "http://10.0.4.25:7890"
      #   NO_PROXY: "localhost,127.0.0.1"
    user: root
    privileged: true
    ports:
      - "3333:22"
    environment:
      TZ: "Asia/Shanghai"
    restart: always
