version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 3230:80
    networks:
      - middleware
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

networks:
  middleware:
    external: true
