version: '3.5'
services:
  rmqnamesrv:
    image: foxiswho/rocketmq:server
    ports:
      - 9876:9876
    volumes:
      - /data/docker/rocketMq/rmqnamesrv/logs:/opt/logs
      - /data/docker/rocketMq/rmqnamesrv/store:/opt/store
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.rmqnamesrv == true

  rmqbroker:
    image: foxiswho/rocketmq:broker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - /data/docker/rocketMq/rmqbroker/logs:/opt/logs
      - /data/docker/rocketMq/rmqbroker/store:/opt/store
      - /data/docker/rocketMq/rmqbroker/brokerconf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rmqnamesrv
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.rmqbroker == true

  rmqconsole:
    image: styletang/rocketmq-console-ng
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.rmqconsole == true

# volumes:
#   rocketMq_rmqnamesrv:
#     external: true
