version: '3'
services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
      - redis_logs:/logs
    command:
      bash -c "echo 'port 6379' > redis.conf  &&
      echo 'requirepass foobared' >> redis.conf  &&

      cat redis.conf &&
      redis-server redis.conf"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

volumes:
  redis_data:
  redis_logs:
