apiVersion: operator.skywalking.apache.org/v1alpha1
kind: SwAgent
metadata:
  name: swagent
  namespace: app-ns
spec:
  containerMatcher: ''
  selector:
    matchLabels: k8s.kuboard.cn/name=app-service
  javaSidecar:
    name: swagent
    image: apache/skywalking-java-agent:8.16.0-java8
    env:
      - name: SW_LOGGING_LEVEL
        value: DEBUG
      - name: SW_JDBC_TRACE_SQL_PARAMETERS
        value: 'true'
      - name: SW_PLUGIN_TOMCAT_COLLECT_HTTP_PARAMS
        value: 'true'
      - name: SW_PLUGIN_SPRINGMVC_COLLECT_HTTP_PARAMS
        value: 'true'
      - name: SW_PLUGIN_HTTPCLIENT_COLLECT_HTTP_PARAMS
        value: 'true'
      - name: SW_PLUGIN_MICRONAUTHTTPCLIENT_COLLECT_HTTP_PARAMS
        value: 'true'
      - name: SW_PLUGIN_MICRONAUTHTTPSERVER_COLLECT_HTTP_PARAMS
        value: 'true'
      - name: SW_PLUGIN_LETTUCE_TRACE_REDIS_PARAMETERS
        value: 'true'
      - name: SW_PLUGIN_JEDIS_TRACE_REDIS_PARAMETERS
        value: 'true'
      - name: SW_PLUGIN_REDISSON_TRACE_REDIS_PARAMETERS
        value: 'true'
      - name: SW_AGENT_NAME
        value: '${HOSTNAME:-appName-k8s}'
      - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
        value: 'skywalking-skywalking-helm-satellite.skywalking:11800'
  sharedVolumeName: "sky-agent"
  optionalPlugins:
    - "webflux"
    - "cloud-gateway-2.1.x"
