version: "3"
services:
  windows:
    image: dockurr/windows
    environment:
      KVM: "N"
      # DEBUG: "Y"
      # ARGUMENTS: "-accel hvf"
      # export https_proxy: http://192.168.1.94:7890
      # http_proxy: http://192.168.1.94:7890
      # all_proxy: socks5://192.168.1.94:7890
    container_name: windows
    # devices:
    #   - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    