version: '3'

services:
  yapi-web:
    image: jayfong/yapi:latest
    ports:
      - 7070:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=183461750@qq.com
      - YAPI_ADMIN_PASSWORD=admin
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - yapi-mongo
    networks:
      - middleware
    deploy:
      mode: replicated
      replicas: 1

  yapi-mongo:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    networks:
      - middleware
    deploy:
      mode: replicated
      replicas: 1

networks:
  middleware:
    external: true
