version: "3.5"

services:

  nginx:
    image: nginx
    environment:
      TZ: "Asia/Shanghai"
      SUB_DOMAIN_WAP: "act.*"
      SUB_DOMAIN_WAP_API: "act-api.* s.*"
      SUB_DOMAIN_WEB: "maclient.*"
      SUB_DOMAIN_WEB_API: "ma-api.*"
    command:
      bash -c "mkdir -p /usr/lib/nginx/proxy_tmp && \
      mkdir -p /usr/lib/nginx/proxy_cache/imgcache && \
      chown -R nginx:nginx /usr/lib/nginx/proxy* && \
      /docker-entrypoint.sh nginx -g 'daemon off;'"
    networks:
      middleware:
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "nginx:/var/log/"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/cors.conf:/etc/nginx/cors.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"

volumes:
  nginx:

networks:
  middleware:
    external: true