apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 10.0.5.167, internalAddress: "10.0.5.167", privateKeyPath: "~/.ssh/id_rsa"}
  - {name: node1, address: 10.0.16.146, internalAddress: "10.0.16.146", privateKeyPath: "~/.ssh/id_rsa"}
  roleGroups:
    etcd:
    - master
    control-plane: 
    - master
    worker:
    - master
    - node1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    internalLoadbalancer: haproxy
    externalDNS: false
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    # version: v1.33.1
    version: v1.23.17
    clusterName: cluster.local
    autoRenewCerts: true
    # containerManager: containerd
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    # multusCNI:
    #   enabled: false
  addons: []