
version: '3.8'

services:
  zoo1:
    image: zookeeper
    networks:
      - middleware
    hostname: zoo1
    ports: # 端口
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    volumes:
      - "zoo1_conf:/conf"
      - "zoo1_data:/data"
      - "zoo1_datalog:/datalog"
    deploy:
      mode: replicated
      replicas: 1

networks:
  middleware:
    external: true

volumes:
  zoo1_conf:
  zoo1_data:
  zoo1_datalog: