version: "3.5"

services:

  nginx:
    image: nginx:1.20
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    command:
      bash -c "mkdir -p /usr/lib/nginx/proxy_tmp && \
      mkdir -p /usr/lib/nginx/proxy_cache/imgcache && \
      chown -R nginx:nginx /usr/lib/nginx/proxy* && \
      /docker-entrypoint.sh nginx -g 'daemon off;'"
    environment:
      - TZ="Asia/Shanghai"
      # 以下为自定义配置文件，用于替换模板变量
      - NGINX_HOST=iuin.xyz
      - NGINX_PORT=80
      - HTTPS_PORT=443
      - SSL_CERT_PEM_PATH=conf.d/cert/cert.pem
      - SSL_CERT_KEY_PATH=conf.d/cert/cert.key
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - nginx_templates:/etc/nginx/templates
      - nginx_log:/var/log/
      - nginx_uploads:/etc/nginx/data/uploads
    networks:
      middleware:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

volumes:
  nginx_templates:
  nginx_log:
  nginx_uploads:

networks:
  middleware:
    external: true