version: "3.5"

services:

  nginx:
    image: nginx:1.20-ext  # 使用Dockerfile构建的镜像，(docker build -t nginx:1.20-ext .)
    environment:
      TZ: "Asia/Shanghai"
    command:
      bash -c "mkdir -p /usr/lib/nginx/proxy_tmp && \
      mkdir -p /usr/lib/nginx/proxy_cache/imgcache && \
      chown -R nginx:nginx /usr/lib/nginx/proxy* && \
      /docker-entrypoint.sh nginx -g 'daemon off;'"
    networks:
      middleware:
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 10000
        published: 10000
        mode: host
      - target: 10001
        published: 10001
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "nginx_log:/var/log/"
      - "nginx_conf.d:/etc/nginx/conf.d"
      - "nginx_uploads:/etc/nginx/data/uploads"

volumes:
  nginx_log:
  nginx_uploads:
  nginx_conf.d:

networks:
  middleware:
    external: true