version: "3.5"

services:

  nginx:
    image: nginx:1.20
    ports:
      - target: 80
        published: 80
        mode: host
    environment:
      - TZ="Asia/Shanghai"
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./templates:/etc/nginx/templates
      - "nginx_log:/var/log/"
      - "nginx_uploads:/etc/nginx/data/uploads"
    networks:
      middleware:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

volumes:
  nginx_log:
  nginx_uploads:

networks:
  middleware:
    external: true