version: "3.5"

services:

  adguard:
    image: adguard/adguardhome
    networks:
      middleware:
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 80
        published: 80
        mode: host
      - target: 3000
        published: 3000
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - adguardhome_work:/opt/adguardhome/work
      - adguardhome_conf:/opt/adguardhome/conf

volumes:
  adguardhome_work:
  adguardhome_conf:

networks:
  middleware:
    external: true