version: "3.5"

services:

  mysql_m1:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    command:
      bash -c ' echo "[mysqld]
      symbolic-links=0 " > /etc/mysql/conf.d/haproxy.cnf docker-entrypoint.sh mysqld'
    ports:
      - target: 3306
        published: 13306
        mode: host
    networks:
      middleware:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mariadb_mysql_m1:/var/lib/mysql

  mysql_m2:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    command:
      bash -c ' echo "[mysqld]
      symbolic-links=0 " > /etc/mysql/conf.d/haproxy.cnf docker-entrypoint.sh mysqld'
    ports:
      - target: 3306
        published: 13307
        mode: host
    networks:
      middleware:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mariadb_mysql_m2:/var/lib/mysql

  haproxy:
    image: haproxy:latest
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    command:
      bash -c ' echo "
      global
        log 127.0.0.1 local0
      defaults
        log global
        retries 2
        timeout connect 3000
        timeout server 5000
        timeout client 5000
      listen mysql-cluster
        bind *:3308
        mode tcp
        option tcp-check
        balance roundrobin
        server mysql-master1 mysql_m1:3306 check
        server mysql-master2 mysql_m2:3306 check
      listen mysql-clusterstats
        bind *:8080
        mode http
        stats enable
        stats uri /
        stats realm Strictly\ Private
        stats auth admin:admin " > /usr/local/etc/haproxy/haproxy.cfg docker-entrypoint.sh haproxy -f /usr/local/etc/haproxy/haproxy.cfg'
    ports:
      - target: 3308
        published: 3308
        mode: host
      - target: 8080
        published: 18080
        mode: host
    depends_on:
      - mysql_m1
      - mysql_m2
    networks:
      middleware:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

volumes:
  mariadb_mysql_m1:
  mariadb_mysql_m2:

networks:
  middleware:
    external: true