
services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    ports:
      - target: 8080
        published: 8888
        mode: host
      - target: 9090
        published: 9999
        mode: host
    volumes:
      # Please change <CONFIG_PATH> to the fullpath of the config folder just created
      - ./config:/etc/headscale
    command: serve
