
services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    # network_mode: "host"  # 直接使用宿主机网络
    restart: unless-stopped
    ports:
      # - target: 8080
      #   published: 8888
      #   mode: host
      # - target: 9090
      #   published: 9999
      #   mode: host
      - "8080:8080"  # HTTP API（可选）
      - "41641:41641/udp"  # Tailscale 默认端口（必须）
      - "3478:3478/udp"    # STUN/TURN 端口（如果使用 TURN，必须）
    environment:
      TS_DEBUG: "1"  # 可选，启用调试日志
    volumes:
      # Please change <CONFIG_PATH> to the fullpath of the config folder just created
      - ./config:/etc/headscale
      - ./headscale_data:/var/lib/headscale  # 持久化数据
    command: serve
