
version: '3.9'

services:

  nginx:
    image: nginx
    privileged: true
    restart: always
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/docker/nginx/html:/usr/share/nginx/html
      - /data/docker/nginx/conf.d:/etc/nginx/conf.d
      # - /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/docker/nginx/cache:/var/cache/nginx
      - /proc:/hostip/:ro
