version: '3.9'

services:

  nginx:
    image: nginx
    networks:
      hostnet: {}
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/docker/nginx/html:/usr/share/nginx/html
      - /data/docker/nginx/conf.d:/etc/nginx/conf.d
      - /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/docker/nginx/cache:/var/cache/nginx
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

networks:
  hostnet:
    external: true
    name: host