version: "3.5"

services:

  nginx:
    image: nginx
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - target: 80
        published: 8888
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/cors.conf:/etc/nginx/cors.conf"
      - "./conf/conf.d/:/etc/nginx/conf.d/"
      - "./html:/usr/share/nginx/html"
