apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-harbor
spec:
  acme:
    # 使用 Let's Encrypt ACME 服务器
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 183461750@qq.com
    privateKeySecretRef:
      name: letsencrypt-harbor
    solvers:
      - http01:
          ingress:
            # 这里应该是要填IngresClass列表中的名称
            class: lingxi-ingress-nginx

