---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: app-service
  name: app-service
  namespace: skywalking
  resourceVersion: '11132165'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: app-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2024-04-07T02:05:41+08:00'
      creationTimestamp: null
      labels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: app-service
    spec:
      containers:
        - env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: 'skywalking-skywalking-helm-oap.skywalking:30004'
            - name: SW_AGENT_NAME
              value: app-service
          image: 'harbor.harbor6/mall/app-service:latest'
          imagePullPolicy: IfNotPresent
          name: app-service
          ports:
            - containerPort: 8911
              hostPort: 8911
              name: api
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: app-service
  name: app-service
  namespace: skywalking
  resourceVersion: '11132157'
spec:
  clusterIP: 10.107.3.4
  clusterIPs:
    - 10.107.3.4
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: api
      nodePort: 30012
      port: 8911
      protocol: TCP
      targetPort: 8911
  selector:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: app-service
  sessionAffinity: None
  type: NodePort

