version: "3.5"

services:

  grafana: # 监控的web-ui好用的可视化组件
    image: grafana/grafana
    networks:
      middleware:
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  prometheus: # 核心监控组件
    image: prom/prometheus
    networks:
      middleware:
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  alertmanager: # 告警组件（目前暂未用到)
    image: prom/alertmanager
    networks:
      middleware:
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  node-exporter: # 用户获取服务器的指标
    image: quay.io/prometheus/node-exporter
    networks:
      middleware:
    ports:
      - target: 9100
        published: 9100
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  cadvisor: # 用于获取docker容器的指标
    image: google/cadvisor:latest
    ports:
      - target: 8899
        published: 8899
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  grafana_log:

networks:
  middleware:
    external: true