version: '3'
services:
  mysql:
    image: "docker.io/mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'root'
      MYSQL_PASS: 'root'
    ports:
      - "3306:3306"
    volumes:
    - $PWD/conf:/etc/mysql/conf.d
    - $PWD/logs:/logs
    - $PWD/data:/var/lib/mysql