version: '3.5'

services:
  app-service:
    env_file:
      - .env
    build:
      context: $PROJECT_ROOT_DIR
      dockerfile: ./deploy/docker/$APP_ENV/app-service/Dockerfile
    restart: on-failure
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8911:8911"
      - "18911:18911"
      - "28911:28911"
      - "38911:38911"
    networks:
      app:

networks:
  app:
    external: true
