version: "3"

services:

  nginx:
    image: "ssyma/nginx:latest"
    environment:
      TZ: "Asia/Shanghai"
      SUB_DOMAIN_ADMIN: "ma-admin.*"
      SUB_DOMAIN_ADMIN_API: "ma-admin-api.*"
      SUB_DOMAIN_IMAGE: "image.*"
      SUB_DOMAIN_JSSDK: "jssdk.*"
      SUB_DOMAIN_MADATA: "madata.*"
      SUB_DOMAIN_STATIC: "static.*"
      SUB_DOMAIN_WAP: "act.*"
      SUB_DOMAIN_WAP_API: "act-api.* s.*"
      SUB_DOMAIN_WEB: "maclient.*"
      SUB_DOMAIN_WEB_API: "ma-api.*"
      SUB_DOMAIN_ZK: "zk.*"
      #      SUB_DOMAIN_HAPROXY: "haproxy.*"
      SUB_DOMAIN_MQ: "mq.*"
      SUB_DOMAIN_DA: "da.*"
    networks:
      shushangyun:
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.client==true

    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./shushangyun/:/data/wwwroot/shushangyun/"
      - "nginx:/var/log/"

volumes:
  nginx:

networks:
  shushangyun:
    external: true