version: '3.5'

services:
  wap-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8081:8080"
      - "28081:28080"
    networks:
      - middleware

networks:
  middleware:
    external: true
