version: "3.5"

services:

  netdata:
    image: netdata/netdata
    networks:
      middleware:
    ports:
      - target: 19999
        published: 19999
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
#    securityContext:
#      privileged: true
#      capabilities:
#        add: ["SYS_PTRACE"]
#    security_opt:
#      - apparmor:unconfined
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro

volumes:
  netdata_config:
  netdata_lib:
  netdata_cache:

networks:
  middleware:
    external: true