
services:
  dev-jumpbox:
    image: registry.cn-hangzhou.aliyuncs.com/iuin/dev-jumpbox:tcpmux
    container_name: dev-jumpbox
    environment:
      TZ: "Asia/Shanghai"
      serverAddr: '"55.44.33.33"'
      serverPort: 18000
      auth_token: '"frps-ssh"'
      client_name: '"frpc-ssh-fa"'
      customDomains: '["fa.intranet.company"]'
    extra_hosts:
      - "me.host:host-gateway"
    restart: unless-stopped
