version: '3.4'

services:

  redis-master:
    image: redis
    networks:
      - redisdb
    ports:
      - 6379:6379
    volumes:
      - redis-master:/data
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  redis-slave:
    image: redis
    networks:
      - redisdb
    command: redis-server --slaveof redis-master 6379
    volumes:
      - redis-slave:/data
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  sentinel:
    image: redis
    networks:
      - redisdb
    ports:
      - 26379:26379
    command: >
      bash -c "echo 'port 26379' > sentinel.conf &&
      echo 'dir /tmp' >> sentinel.conf &&
      echo 'sentinel monitor redis-master redis-master 6379 2' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds redis-master 5000' >> sentinel.conf &&
      echo 'sentinel parallel-syncs redis-master 1' >> sentinel.conf &&
      echo 'sentinel failover-timeout redis-master 5000' >> sentinel.conf &&
      cat sentinel.conf &&
      redis-server sentinel.conf --sentinel"
    depends_on:
      - redis-master
      - redis-slave
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

volumes:
  redis-master:
    driver: local
  redis-slave:
    driver: local

networks:
  redisdb:
    attachable: true
    driver: overlay