version: '3'
services:
  redis:
    image: redis
    volumes:
      - /data/docker/redis/data:/data
      - /data/docker/redis/config/redis.conf:/etc/redis/redis.conf
      - /data/docker/redis/logs:/logs
    command: redis-server /docker/config/redis.conf
      #      两个写入操作 只是为了解决启动后警告 可以去掉
#      /bin/bash -c "echo 511 > /proc/sys/net/core/somaxconn
#      && echo never > /sys/kernel/mm/transparent_hugepage/enabled
#      && redis-server /etc/redis/redis.conf"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.redis_master == true
