version: '3.4'

services:

  redis-master:
    image: redis:6.0
    networks:
      - redisdb
    volumes:
      - redis-master:/data
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  redis-slave:
    image: redis:6.0
    networks:
      - redisdb
    command: redis-server --slaveof redis-master 6379
    volumes:
      - redis-slave:/data
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  sentinel:
    image: redis:6.0
    networks:
      - redisdb
    command:
      bash -c "echo 'port 26379' > sentinel.conf &&
      echo 'sentinel monitor mymaster redis-master 6379 2' >> sentinel.conf &&
      echo 'sentinel down-after-milliseconds mymaster 5000' >> sentinel.conf &&
      echo 'sentinel failover-timeout mymaster 60000' >> sentinel.conf &&
      echo 'sentinel parallel-syncs mymaster 1' >> sentinel.conf &&
      cat sentinel.conf &&
      redis-sentinel sentinel.conf"
    depends_on:
      - redis-master
      - redis-slave
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

volumes:
  redis-master:
    driver: local
  redis-slave:
    driver: local

networks:
  redisdb:
    attachable: true
    driver: overlay