version: "3"

services:

  rmqnamesrv:
    image: "rocketmqinc/rocketmq:4.4.0"
    command: "sh mqnamesrv"
    environment:
      MAX_POSSIBLE_HEAP: 1000000000
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "rmqnamesrv:/root"
    networks:
      iuin:
    deploy:
      placement:
        constraints:
          - node.labels.mq==true
  rmqbroker:
    image: "rocketmqinc/rocketmq:4.4.0"
    depends_on:
      - rmqnamesrv
    command: "sh mqbroker -c /opt/rocketmq-4.4.0/conf/broker.conf"
    environment:
      MAX_POSSIBLE_HEAP: 1000000000
      NAMESRV_ADDR: "rmqnamesrv:9876"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./rocketmq/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf"
      - "rmqbroker:/root"
    networks:
      iuin:
    deploy:
      placement:
        constraints:
          - node.labels.mq==true
  mqui:
    image: "styletang/rocketmq-console-ng"
    depends_on:
      - rmqnamesrv
      - rmqbroker
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    networks:
      iuin:
    deploy:
      placement:
        constraints:
          - node.labels.mq==true
networks:
  iuin:
    external: true

volumes:
  rmqnamesrv:
  rmqbroker:
