version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: aeert/openvpn:latest
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    depends_on:
      - "gui"
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
  gui:
    image: aeert/openvpn-web:latest
    container_name: openvpn-gui
    ports:
     - "8080:8080/tcp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
     - ./openvpn-data/db:/opt/openvpn-gui/db


#
#username: admin
#password: b3secure